### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by gatlinnewhouse** [jamesnewhouse/pyrrhic#4]
- [ ] Add separate blogs for David and I

- [https://stackoverflow.com/questions/14560687/multiple-blogs-in-single-jekyll-website](https://stackoverflow.com/questions/14560687/multiple-blogs-in-single-jekyll-website)

- [https://www.garron.me/en/blog/multi-blog-site-jekyll.html](https://www.garron.me/en/blog/multi-blog-site-jekyll.html)

- [ ] Add installation script for Mac

- [ ] Change theme a bit

**Comment by gatlinnewhouse** [comment]
Repo is now at last working published page.

Now I can begin working on these things
